### PR TITLE
Submodules back to classes

### PR DESCRIPTION
**Pull request by juanep97**
New file structure as discussed in #8.

### CODE REVIEW

**Comment by Bultako** [comment]
Thanks @jjjon 

just one minor comment, please replace `from mutis.correlation.functions import kroedel_ab` by `from mutis.lib.correlation import kroedel_ab` in `lib/correlation.py`. 

Once this PR merged I will migrate docs to [ https://readthedocs.org]( https://readthedocs.org) so to have the built docs separated from the code repo and have much more cleaner PRs.

**Review by Bultako — CHANGES_REQUESTED** [review]
see comments above

**Comment by juanep97** [comment]
@Bultako I can't find that line you want me to replace, there is only a
```Python
from mutis.lib.correlation import *
```
in `mutis/correlation.py` if that's what you mean?

**Comment by Bultako** [comment]
> @Bultako I can't find that line you want me to replace, there is only a
> 
> ```python
> from mutis.lib.correlation import *
> ```
> 
> in `mutis/correlation.py` if that's what you mean?

no, I mean in [lib/correlation.py](https://github.com/IAA-CSIC/MUTIS/blob/d6e7c5bd7582ada8ebaac925f357d82665740a32/mutis/lib/correlation.py#L56) in the version of the files of this PR

**Comment by juanep97** [comment]
Ah, didn't see that. Done. I merge.

**Pull request merged**
